apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "registry.edgaryasociados.synology.me": {
          "username": "admin",
          "password": "siq7hVFNE7DHP2EGHCku",
          "auth": "YWRtaW46c2lxN2hWRk5FN0RIUDJFR0hDa3U="
        }
      }
    }
